### ISSUE TITLE
Change executable from python to python3 for non-Windows systems

### ISSUE THREAD

**Issue by DavesCodeMusings** [DavesCodeMusings/mpremote-vscode#16]
Currently for non-Windows systems, the executable used to run mpremote commands is `python`. It's probably more appropriate to use `python3`. While systems may symlink `python` to `python3`, it's best not to rely on this behavior.

Comments from Linux / OSX users are welcome before this change is made.

**Comment by ccoupe** [comment]
At least the way my python is setup on OSX via homebrew installion,  there is no 'python' executable - just python3 - a symlink from python to python3 works well for a short term fix but as you say Apple and/or  Homebrew have a habit of undoing things.

**Comment by DavesCodeMusings** [comment]
Implemented in 1.21.5
