### ISSUE TITLE
Error running command mpremote.refreshSerialPorts

### ISSUE THREAD

**Issue by Wind-stormger** [DavesCodeMusings/mpremote-vscode#7]
![image](https://github.com/DavesCodeMusings/mpremote-vscode/assets/76462385/5084fffd-2ff5-4361-bd32-397a40071f09)

Error running command mpremote.refreshSerialPorts: command 'mpremote.refreshSerialPorts' not found. This is likely caused by the extension that contributes mpremote.refreshSerialPorts.

Python 3.11.0
mpremote 1.20.0

**Comment by DavesCodeMusings** [comment]
What version of the extension are you using? I'm not able to reproduce this and I'm using v1.20.16 of the extension.

**Comment by DavesCodeMusings** [comment]
Unable to reproduce.
